services:
  postgres:
    container_name: postgres-todo
    image: postgres:15.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

